# Generated by Django 2.1.7 on 2019-10-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('total_cost', models.IntegerField(default=0)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_received', models.BooleanField(default=False)),
                ('received_date', models.DateField(null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('return_date', models.DateField(null=True)),
                ('cost', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='checkout.Order')),
            ],
        ),
    ]
