# Generated by Django 2.1.7 on 2019-10-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20191008_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='request_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
